export default {
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    FETCH_USER_DETAILS_SUCCESS: 'FETCH_USER_DETAILS_SUCCESS',
    FETCH_USER_DETAILS_FAILURE: 'FETCH_USER_DETAILS_FAILURE',

    FETCH_PRODUCT_LIST: 'FETCH_PRODUCT_LIST',
    FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
    FETCH_PRODUCT_LIST_FAILURE: 'FETCH_PRODUCT_LIST_FAILURE',

    SHOW_APP_LOADER: 'SHOW_APP_LOADER',
    HIDE_APP_LOADER: 'HIDE_APP_LOADER',
}